LinkedIn/__init__.py
from flask import Flask, render_template, request
from flask_login import LoginManager, current_user
import os

from dotenv import load_dotenv

load_dotenv()

def create_app():
    app = Flask(__name__)
    app.secret_key = os.getenv("secret_key")
    app.config['secret_key'] = os.getenv("Secret_key")
    app.config['UPLOAD_FOLDER'] = "LinkedIn/static/uploads"
    app.config['PROFILE'] = "LinkedIn/static/profile"

    from .auth import auth
    from .views import views
    from .mongo import mongo

    app.register_blueprint(auth, url_prefix = "/")
    app.register_blueprint(views, url_prefix = "/")
    app.register_blueprint(mongo, url_prefix = "/")

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .model import User
    from .sqlite import getUserById

    @login_manager.user_loader
    def load_user(id):
        data = getUserById(id)
        if data:
            cur_user = User(id=data[0][0], username=data[0][1], password=data[0][2], email=data[0][3], type=data[0][4])
            return cur_user
        
    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('404.html'), 404

    @app.errorhandler(500)
    def internal_server_error(error):
        return render_template('500.html'), 500
        
    @app.before_request
    def log_before_request():
        app.logger.info('Global Middleware - Response header: %s', request.headers)

    @app.after_request
    def log_after_request(response):
        app.logger.info('Global Middleware - Response Status: %s', response.status)
        return response        

    return app

LinkedIn/auth.py
from flask import Blueprint, redirect, render_template, url_for, current_app, flash
from .model import SignupForm, LoginForm
from .sqlite import insertDataIntoUsers, authenticate, getUsername
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from .model import User

auth = Blueprint("auth", __name__)


@auth.route('/signup', methods=['GET', 'POST'])
def sign_up():
    form = SignupForm()

    if form.validate_on_submit():

        username = form.username.data
        email = form.email.data
        password = form.password.data
        pro_type = form.pro_type.data

        hash_password = generate_password_hash(password)

        insertDataIntoUsers(username, email, hash_password, pro_type)
        return redirect(url_for('views.homepage'))
        
    return render_template('signup.html', form=form)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if current_user.is_authenticated:
        return redirect(url_for('views.homepage'))

    if form.validate_on_submit():

        username = form.username.data
        password = form.password.data

        data = authenticate(username)
        if data:
            if check_password_hash(data[2], password):
                user = User(id=data[0], username=data[1], password=data[2], email=data[3], type=data[4])
                login_user(user)
                flash("Successfully logged In", category="success")
                return redirect(url_for('views.homepage'))
            else:
                flash("Login Failed! check your password", category="error")
                return redirect(url_for('auth.login'))
        else:
            flash("Email does not exists! create an account", category="error")
            return redirect(url_for('auth.login'))

    return render_template('login.html', form=form)


@auth.route('/employer_login')
def employer_login():
    form = LoginForm()
    return render_template('employer_login.html', form=form)

@auth.route('/employer_signUp')
def employer_signUp():
    form = SignupForm()
    return render_template('employer_signUp.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

LinkedIn/views.py
from flask import Blueprint, render_template, current_app, request
from flask_login import login_required, current_user
from .mongo import jobs

views = Blueprint("views", __name__)

@views.route('/')
@login_required
def homepage():
    job_details = list(jobs.find())
    return render_template('homepage.html', job_details=job_details)

LinkedIn/templates/auth_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% block css%} {{ url_for('static', filename='css/base.css') }} {% endblock %}"> 
    <title>{% block header %}{% endblock %}</title>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="margin-right: 5;">SeekedIn</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" aria-current="page" href="#">Articles</a>
              <a class="nav-link" href="#">People</a>
              <a class="nav-link" href="#">Learning</a>
              {% block nav %}<a class="nav-link" href="{{ url_for('auth.employer_signUp') }}">employer</a>{% endblock %}
            </div>
          </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories="true") %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == "error" %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="a-container">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block script %}{% endblock %}

</body>
</html>

LinkedIn/templates/createJobs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>createJobs</title>
</head>
<body>
    <h1>createJobs</h1>
    <form action="{{ url_for('mongo.createJobs') }}" method="post" enctype="multipart/form-data">
        <label for="jobTitle">Job Title:</label>
        <input type="text" id="jobTitle" name="jobTitle" required><br>

        <label for="jobDescription">Job Description:</label>
        <textarea id="jobDescription" name="jobDesc" rows="4" required></textarea><br>

        <label for="location">Location:</label>
        <input type="text" id="location" name="location" required><br>

        <label for="companyName">Company Name:</label>
        <input type="text" id="companyName" name="companyName" required><br>

        <label for="salaryRange">Salary Range:</label>
        <input type="text" id="salaryRange" name="salaryRange"><br>

        <label for="duration">Duration:</label>
        <input type="text" id="duration" name="duration"><br>

        <label for="requirements">requirements:</label>
        <input type="text" id="requirements" name="requirements"><br>

        <label for="img" class="form-label">choose an img: </label>
        <input type="file" name="image"><br>

        <input type="submit" value="Submit">
    </form>
</body>
</html>

LinkedIn/templates/employer_signUp.html
{% extends "auth_template.html"%}

{% block css %}{{ url_for('static', filename='css/auth.css')}}{% endblock %}

{% block title %}Sign Up{% endblock %}

{% block nav %}<a class="nav-link" href="{{ url_for('auth.login') }}">employee</a>{% endblock %}

{% block content%}
<section class="Form my-5 mx-5 myForm">
    <div class="container-fluid customCont">
        <div class="row no-gutters customCont">
            <div class="col-lg-8 nopadding">
                <img src="{{ url_for('static', filename='logo/background-img.jpg') }}" class="img" alt="...">
            </div>
            <div class="col-lg-4 my-5 cusCont">
                <h2 class="text-center">Sign Up for employer</h2>
                <form action="{{url_for('auth.sign_up')}}" method="post">
                    {{ form.hidden_tag() }}

                    <div class="form-group m-3">
                        {{ form.pro_type.label(class="form-control-label visually-hidden") }}
                        {{ form.pro_type(value="employer", class="form-control visually-hidden") }}
                        {% for error in form.username.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.username.label(class="form-control-label") }}
                        {{ form.username(class="form-control") }}
                        {% for error in form.username.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.email.label(class="form-control-label") }}
                        {{ form.email(class="form-control") }}
                        {% for error in form.email.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.password.label(class="form-control-label") }}
                        {{ form.password(class="form-control") }}
                        {% for error in form.password.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {{ form.confirm_password(class="form-control") }}
                        {% for error in form.confirm_password.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>

                    <div class="text-center"><a href="{{ url_for('auth.login') }}">Already have an account? Log In</a></div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

LinkedIn/templates/homepage.html
{% extends "navbar.html" %}

{% block css %}{{ url_for('static', filename='css/homepage.css') }}{% endblock %}

{% block header %}SeekedIn{% endblock %}

{% block content %}

<!-- Main Content -->
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-8">
            <h3 class="mb-3">LinkedIn Feed</h3>

            <!-- Feed content goes here -->
            {% for job in job_details %}
                {% for details in job.job_info %}
                    <div class="card mb-3">
                        <div class="card-header">
                            <div class="media" style="display: flex; height: 40px;">
                                <img src="{{ url_for('static', filename='profile/'~ details.profile_image) }}" class="mr-3 rounded-circle" alt="Profile Picture" style="width: 40px;">
                                <div class="media-body mx-3">
                                    <h5 class="mt-0 mb-0">{{ details.username }}</h5>
                                    <p class="text-muted">Last updated 3 mins ago</p>
                                </div>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename='uploads/' ~ details.image) }}" class="card-img-top" alt="Post Image" style="height: 75vh;">
                        <div class="card-body">
                            <p class="card-text">Company Name: {{ details.companyName }}</p>
                            <p class="card-text">Job title: {{ details.job_title }}</p>
                            <p class="card-text">job description: {{ details.jobDesc }}</p>
                            <p class="card-text">location: {{ details.location }}</p>
                            <p class="card-text">duration: {{ details.duration }}</p>
                            <p class="card-text">requirements: {{ details.requirements }}</p>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <button type="button" class="btn btn-link">Like</button>
                                    <button type="button" class="btn btn-link">Comment</button>
                                    <button type="button" class="btn btn-link"><a href="{{ url_for('mongo.applications', job_id = details.job_id) }}">Apply</a></button>
                                </div>
                                <div>
                                    <small class="text-muted">25 Likes</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}


        </div>
        <div class="col-lg-4">
            <h3 class="mb-4">Your Network</h3>
        
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ url_for('static', filename='profile/default_profile.avif') }}" alt="User 1" class="img-fluid">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">User 1</h5>
                            <p class="card-text">Web Developer</p>
                            <button class="btn btn-primary">Connect</button>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ url_for('static', filename='profile/default_profile.avif') }}" alt="User 2" class="img-fluid">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">User 2</h5>
                            <p class="card-text">Designer</p>
                            <button class="btn btn-primary">Connect</button>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ url_for('static', filename='profile/default_profile.avif') }}" alt="User 3" class="img-fluid">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">User 3</h5>
                            <p class="card-text">Entrepreneur</p>
                            <button class="btn btn-primary">Connect</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
</div>

{% endblock %}

{% block script %}{% endblock %}

 

LinkedIn/templates/login.html
{% extends "auth_template.html"%}

{% block title %}Login{% endblock %}

{% block css %}{{ url_for('static', filename='css/auth.css')}}{% endblock %}

{% block content%}
<section class="Form my-5 mx-5 myForm">
    <div class="container-fluid customCont">
        <div class="row no-gutters customCont">
            <div class="col-lg-8 nopadding">
                <img src="{{ url_for('static', filename='logo/background-img.jpg') }}" class="img" alt="...">
            </div>
            <div class="col-lg-4 my-5 cusCont">
                <h2 class="text-center">Log in</h2>
                <form action="{{url_for('auth.login')}}" method="post">
                    {{ form.hidden_tag() }}

                    <div class="form-group m-3">
                        {{ form.username.label(class="form-control-label") }}
                        {{ form.username(class="form-control") }}
                        {% for error in form.username.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.password.label(class="form-control-label") }}
                        {{ form.password(class="form-control") }}
                        {% for error in form.password.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>

                    <div class="text-center"><a href="{{ url_for('auth.sign_up') }}">Don't have an account? Sign Up</a></div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

LinkedIn/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% block css%} {{ url_for('static', filename='css/base.css') }} {% endblock %}"> 
    <title>{% block header %}{% endblock %}</title>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav ps-3 ">
                <a class="nav-item nav-link" id="home" href="{{ url_for('views.homepage') }}">home</a>
                <a class="nav-item nav-link" id="profile" href="{{ url_for('mongo.profile') }}">Profile</a>
                {% if current_user.type == 'employer' %}
                    <a class="nav-item nav-link" id="createJobs" href="{{ url_for('mongo.createJobs') }}">create job</a>
                {% else %}
                    <a class="nav-item nav-link" id="viewApplications" href="{{ url_for('mongo.viewApplications') }}">applications</a>
                {% endif %}
                <a class="nav-item nav-link" id="logout" href="{{ url_for('auth.logout') }}">Logout</a>
                <form class="d-flex ms-5" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="width: 400px;">
                </form>
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories="true") %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == "error" %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="a-container">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block script %}{% endblock %}

</body>
</html>

LinkedIn/templates/profile.html
{% extends "navbar.html" %}

{% block css %}{{ url_for('static', filename='css/profile.css') }}{% endblock %}

{% block header %}Profile{% endblock %}

{% block content %}

<div class="container mt-5">
    <h2>User Profile</h2>
    <form action="{{ url_for('mongo.profile') }}" method="POST" enctype="multipart/form-data">
        <div class="form-group mb-3 mt-4">
            <label for="avatar">profile Picture:</label>
            <input type="file" class="form-control-file" id="profile_image" name="profile_image">
        </div>
        
        <div class="form-group">
            <label for="address">location:</label>
            <input type="text" class="form-control" id="location" name="location">
        </div>
        
        <div class="form-group mb-3">
            <label for="phone">Phone:</label>
            <input type="text" class="form-control" id="contact" name="contact">
        </div>
        
        <button type="submit" class="btn btn-primary">Save details</button>
    </form>
</div>

{% endblock %}

LinkedIn/templates/signup.html
{% extends "auth_template.html"%}

{% block css %}{{ url_for('static', filename='css/auth.css')}}{% endblock %}

{% block title %}Sign Up{% endblock %}

{% block content%}
<section class="Form my-5 mx-5 myForm">
    <div class="container-fluid customCont">
        <div class="row no-gutters customCont">
            <div class="col-lg-8 nopadding">
                <img src="{{ url_for('static', filename='logo/background-img.jpg') }}" class="img" alt="...">
            </div>
            <div class="col-lg-4 my-5 cusCont">
                <h2 class="text-center">Sign Up</h2>
                <form action="{{url_for('auth.sign_up')}}" method="post">
                    {{ form.hidden_tag() }}

                    <div class="form-group m-3">
                        {{ form.pro_type.label(class="form-control-label visually-hidden") }}
                        {{ form.pro_type(value="employee", class="form-control visually-hidden") }}
                        {% for error in form.username.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.username.label(class="form-control-label") }}
                        {{ form.username(class="form-control") }}
                        {% for error in form.username.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.email.label(class="form-control-label") }}
                        {{ form.email(class="form-control") }}
                        {% for error in form.email.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.password.label(class="form-control-label") }}
                        {{ form.password(class="form-control") }}
                        {% for error in form.password.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {{ form.confirm_password(class="form-control") }}
                        {% for error in form.confirm_password.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
        
                    <div class="form-group m-3">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>

                    <div class="text-center"><a href="{{ url_for('auth.login') }}">Already have an account? Log In</a></div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

LinkedIn/templates/viewApplications.html
{% extends "navbar.html" %}

{% block css %}{{ url_for('static', filename='css/applications.css') }}{% endblock %}

{% block header %}Applications{% endblock %}

{% block content %}
{% if appl %}
    {% for details in appl %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ url_for('static', filename='uploads/'~ details.image) }}" class="img-fluid" alt="Job Image">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ details.job_title }}</h5>
                        <p class="card-text">Company: {{ details.company_name }}</p>
                        <p class="card-text">Salary Range: {{ details.salary_range }}</p>
                        <p class="card-text">Duration: {{ details.duration }}</p>
                        <p class="card-text">Employer Email: {{ details.email }}</p>
                        <p class="card-text">Employee: {{ details.employee }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <small class="text-muted">Employer: {{ details.employer }}</small>
            </div>
        </div>
    {% endfor %}
{% else %}
    <h3 class="text-center mt-5">No Applications</h3>
{% endif %}

{% endblock %}